version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001

  freqtrade-gucky:
    image: freqtradeorg/freqtrade:stable
    volumes:
      - ./user_data_gucky:/freqtrade/user_data
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config-hl-gucky.json
      --strategy SampleStrategy
    environment:
      FREQTRADE_API_KEY: ${GUCKY_API_TOKEN}

  freqtrade-elliot:
    image: freqtradeorg/freqtrade:stable
    volumes:
      - ./user_data_elliot:/freqtrade/user_data
    ports:
      - "8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config-elliotv5.json
      --strategy SampleStrategy
    environment:
      FREQTRADE_API_KEY: ${ELLIOT_API_TOKEN}

  freqtrade-macd:
    image: freqtradeorg/freqtrade:stable
    volumes:
      - ./user_data_macd:/freqtrade/user_data
    ports:
      - "8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config-macd.json
      --strategy SampleStrategy
    environment:
      FREQTRADE_API_KEY: ${MACD_API_TOKEN}

  freqtrade-vwap:
    image: freqtradeorg/freqtrade:stable
    volumes:
      - ./user_data_vwap:/freqtrade/user_data
    ports:
      - "8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config-vwap.json
      --strategy SampleStrategy
    environment:
      FREQTRADE_API_KEY: ${VWAP_API_TOKEN}